### ISSUE TITLE
How to get motor controller board to work with Pi 5?

### ISSUE THREAD

**Issue by Starman7312** [CamJam-EduKit/EduKit3#36]
I recently got a pi 5, with AI kit - hoping to use the kit with it to create an AI powered robot. However the motor controller board won’t work. It doesn’t even power up? No lights at all on top (it does still work with pi 4B).

I’m aware that the GPIO pins have been redesigned for pi 5, and are no longer run on chip - however their orientation stayed the same so can this work and if so how?

I tried running robot code and get multiple errors, such as:
“warning (from warnings module) :
File /us/Lib/python3/dist-packages/gpiozero/devices.py", Line 300 warnings warni
PinFactoryFallback: Falling back from Igpio: [Errno 2] No such file or directory
#-Lgd-nfy-3*
Traceback (most recent call Last):
File "/us/lib/python3/dist-packages/gpiozero/pins/pi.Py", line 411, in pin
pin = self-pins[info]
KeyError: PinInto(number=21, name='GPIO9'
: BOAR0217, 9, GPT09, WA113'1), putow-11,cot-1,ntertaces-frozenset
(C'' "uart', 'spi'. 'dpi', '12c*, "gpio'}))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/media/henry/USB DISK1/Pi Documents Backup/Documents/Robotic Car Project /Source Code/Robotic Car Code-Py", line 4, in ‹module>
robot = CamJamKitRobot()
File "/usr/lib/python3/dist-packages/gpiozero/devices.Py", Line 108, in __call
self = super ().__call_(*args, **kwargs)
File "/usr/lib/python3/dist-packages/gpiozero/boards.py", Line 2343, in init
Left=Motor ('BOARD21', 'BOARD19', pum=pwm, pin_factory=pin_factory),
File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 108, in call
Fife/usT/120/python3/1st-packages/gplozero/utput.devtces.py. tine 1197, 1
n Init
('forward _device', PinClass(forward, pin_factory=pin_factory)).
File "/usr/lib/python3/dist-packages/gpiozero/devices.py", Line 108, in _call
self = super ()._ call__(*args, **kwargs)
File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py". Line 392, in _init
super()- init_ (pin, active_high=active_high, initial_value=None,
File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 74, in
AnIL
super(- Init(pin, pin_factory=pin_factory)
File "/usr/11b/python3/dist-packages/gpiozero/mixins-py", line 75, in _init super (). init__(*args, **kwargs)
File "/usr/lib/python3/dist-packages/gpiozero/devices.py". line 553, in _init
pin = self, pin_factory-pin(PIn)
File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", Line 413, in pin
pin = self-pin_class(self, info)
File "/usr/Lib/python3/dist-packages/gpiozero/pins/rpigpio.py". Line 101, in -
InIT
GPIO setup(self, number, GPIO. IN, self. GPIO PULL UPS[self-_pulL])
RuntimeError: Cannot determine SOC peripheral base address
Ln: 83 Col: 1 “

I would appreciate help on how to get it to work with Pi 5. Thanks in advance, Henry 😎

![IMG_4022](https://github.com/user-attachments/assets/a3e30b4e-7a8a-41f2-a75b-0ebfc464e132)

**Comment by GeekyTim** [comment]
Sorry for the delay. I have been looking at this issue and believe I know the issue and how to fix it. I will respond with the solution very soon.

**Comment by Starman7312** [comment]
Thanks @GeekyTim, please keep me posted

**Comment by GeekyTim** [comment]
I found a similar issue with a different HAT on the Pi 5 when I was using a virtual environment, but not allowing the venv to access the GPIO libraries required by GPIO Zero. 

So this issue may depend on if you are using a virtual environment or not, and which version of the OS you are using.

Try creating a venv with:

python3 -m venv CamJam3-venv

And installing libraries with:

./CamJam3-venv/bin/python -m pip install gpiozero
./CamJam3-venv/bin/python -m pip install lgpio

Let me know how that goes. I've not got a spare Pi 5 with accessible GPIO available at the moment.

**Comment by Starman7312** [comment]
Pi 5 GPIO pin issues
------------------------------------
Sorry been busy, but just got round to testing and it didn't work I'm afraid.

I'm now sure the issue isn't code related as I don't get any errors now I moved the file onto the system disk - the board just isn't working on Pi 5.

I recon it's a power issue, as the board lights up when connected to my Pi 4B, but not Pi 5.

------------------------------------
Having done some testing with break out wires, the board only required 4 pins to light up both the green and red LED's (see image 1) - 15RXD, GND, 14TXD and 4.

So I set up a led to test the power output of these pins. On my pi4B, the 15RXD and GNF light the LED - but on my Pi 5 they don't. (See image 2,3) I clearly think something is wrong here.

The I tried the 14TXD and 4, also no light. However swapping the polarity of the 14TXD and 4 does cause a light on pi 5, but not on pi 4B???

So it makes sense the board isn't lighting up, it's not getting the correct power from certain pins.

I've tried lots of wiring combinations for the 4 necessary pins, but I can only ever get the red on the board using Pi 5, not both the required lights. However I can get it to work fine on pi 4B using just the 4 wires.

Something is definitely causing an issue on the pi 5.

------------------------------------
Do you think I've just got a bad pi 5, with messed up GPIO pins? Or is there something else at work here?

Image 1:
![image](https://github.com/user-attachments/assets/609736ed-00db-4f45-8d89-e5a48c675fca)

Image 2:
![image](https://github.com/user-attachments/assets/a7c0e584-5163-496d-9ba4-058f3de7e383)

Image 3:
![image](https://github.com/user-attachments/assets/6a5015c0-3731-4cc3-a7f1-f7614287159e)

**Comment by Starman7312** [comment]
@GeekyTim, I know you didn't have a spare Pi 5 to test it in before, but if you do now would it be possible for you just to connect the motor control board and see if it lights up on boot - so I'll know if it's an issue with my Pi 5 then?

If not has anyone else got this working on Pi 5?

**Comment by GeekyTim** [comment]
I have still not got a spare Pi 5! They seem to get used each time I get a new one. However, I'll see if I can borrow one from a friend.

**Comment by Starman7312** [comment]
Ok thank you, that would be much appreciated @GeekyTim. 😎

**Comment by GeekyTim** [comment]
I have checked with my fellow CamJam/robotic friends and they have definitely had the edukit working on a Pi 5.

However, I am borrowing one, so I will test it myself and see if I have any issues.

**Comment by Starman7312** [comment]
Ok that's great, just let me know the results.

**Comment by GeekyTim** [comment]
I've borrowed a Pi 5 and installed the latest RPi OS, updated it, and cloned the GitHub repository.  I'm afraid that it all worked first time for me.

Please note that the board uses GPIO 9 & 11 to control Motor A, and GPIO 7 & 8 for Motor B.  Worksheet 3 has a diagram indicating those. If you have turned on SPI (in raspi-config) I get the error that GPIO is busy.  You might want to ensure that SPI is disabled.

**Comment by Starman7312** [comment]
Ok @GeekyTim, thank you so much for confirming that.

Just a quick question does the board light up on Pi 5 or not? (Green and or Red LED)

Also I've checked my settings and they're ok, so I've ordered a replacement motor controller board to see if it's the issue.

Just to check isn't the motor A GPIO 9,10? Agreed about the left one.

If no success I'll send back my Pi 5.

Thanks again,
Henry

**Comment by GeekyTim** [comment]
Sorry, yes, 9 & 10.

**Comment by Starman7312** [comment]
Ok I've got it working now, must have accidentally damaged my motor board. Thanks for the support.

Just worth noting that the board lights up in Pi 4B and not on Pi 5.
Which is a result in the difference in functionality of the 15RXD and 14TXD pins.

However the lights have no bearing on its functionality for controlling motors.

Thanks for all the help, and sorry I didn't spot the faulty motor board earlier!

**Comment by Starman7312** [comment]
Have just noticed something weird though, shutting down the Pi 5 activates motor B???

Any ideas what's going on?

**Comment by GeekyTim** [comment]
Interesting about the LED. Not noticed it myself.

As for motor B, I suspect the signal is going high on that pin when the Pi turns off.

**Comment by Starman7312** [comment]
Really, that is odd about the LED's. Anyway seems to have no bearing on functionality thankfully.

Yep I guessed that too, wonder why the OS is doing that though (it didn't on Pi 4B).

**Comment by Starman7312** [comment]
So I made a quick python script to fix the issue and it works when run:

------------------------------------
from gpiozero import CamJamKitRobot

robot = CamJamKitRobot()
robot.stop()

------------------------------------

But if I use the cmd line to execute it (not IDlE) the effect stops after the cmd line python environment is terminated.

Weirdly the effect's remain when using IDLE even after the shell or IDLE script are terminated.

Any ideas? I just want it to work via cmd line, so I can automate the script in boot.

Note: motor turns on, during boot and shutdown

**Comment by Starman7312** [comment]
Ok I fixed it...finally!

I had to add the line below to config.txt:

It just turns the pin off on boot.

------------------------------------
gpio=9=op,dl

------------------------------------

Must be something in the OS causing pin 9 to be set to high (on) by default.

Worth noting this only fixes the issue on boot, it still occurs on shutdown (but that’s not so bad for me), as I can just unplug the Pi or turn off the batteries.

Weird, that it's changed between Pi 5 and 4B - might be worth adding a note about this somewhere on the GitHub repo?
